location __PATH__/ {
    proxy_pass         http://127.0.0.1:__PORT__/;
    proxy_set_header   Host              $host;
    proxy_set_header   X-Real-IP         $remote_addr;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;

    # SSOwat injecte X-Auth-User après authentification
    # (auth_header = true dans le manifest)
    proxy_set_header   X-Auth-User       $http_x_auth_user;

    # L'API bypass SSOwat — on laisse Flask gérer l'auth par token
    more_clear_input_headers 'Accept-Encoding';
}
