#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# BACKUP APP DIR
#=================================================
ynh_script_progression "Backing up application files..."

ynh_backup "$install_dir/app.py"
ynh_backup "$install_dir/requirements.txt"
ynh_backup "$install_dir/static"
ynh_backup "$install_dir/env"

#=================================================
# BACKUP DATA DIR
#=================================================
ynh_script_progression "Backing up data directory..."

ynh_backup "$data_dir"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Backup script completed for $app."
