#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing $app service..."

ynh_systemctl --service="$app" --action=stop
yunohost service remove "$app"
ynh_config_remove_systemd

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx configuration..."

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
