#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing $app service..."

ynh_systemd_action --service_name="$app" --action="stop"
yunohost service remove "$app"
ynh_remove_systemd_config

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx configuration..."

ynh_remove_nginx_config

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
