#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RESTORE APPLICATION FILES
#=================================================
ynh_script_progression "Restoring application files..."

ynh_restore "$install_dir/app.py"
ynh_restore "$install_dir/requirements.txt"
ynh_restore "$install_dir/static"
ynh_restore "$install_dir/env"

python3 -m venv "$install_dir/venv"
"$install_dir/venv/bin/pip" install --upgrade pip
"$install_dir/venv/bin/pip" install -r "$install_dir/requirements.txt"

chown -R "$app:www-data" "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:$app" "$install_dir/venv"
chmod 600 "$install_dir/env"
chown "$app:$app" "$install_dir/env"

#=================================================
# RESTORE DATA DIR
#=================================================
ynh_script_progression "Restoring data directory..."

ynh_restore "$data_dir"
chown -R "$app:$app" "$data_dir"
chmod 750 "$data_dir"

#=================================================
# RESTORE CONFIGS AND RESTART
#=================================================
ynh_script_progression "Restoring configurations..."

ynh_add_systemd_config
ynh_add_nginx_config

ynh_systemd_action --service_name="$app" --action="restart" --log_path="systemd" --line_match="Running on"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Restoration completed for $app"
